codecov:
  branch: master

coverage:
  range: 50..75
  status:
    patch: false
    project:
      default:
        threshold: 5

ignore:
  - sources/Eigen/.*
  - sources/Eigen/**/*
  - sources/Eigen/src/.*
  - sources/tinycompo.hpp
